[package]
name = "test_godot"
version = "0.1.0"
authors = ["Sn0wB <pana.sonia@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.8"